[package]
name    = "example-rust"
version = "1.0.0"
authors = ["watawuwu@3bi.tech"]
exclude = ["examples/*", "tests/*", "benches/*", "*.png", "perf/*", "assets", "Makefile", "tmp.rs"]
readme  = "README.md"

[[bin]]
name = "example-rust"
path = "src/main.rs"

